package com.kiemtragiuaky.controller;
import com.kiemtragiuaky.entity.Book_24133028; import com.kiemtragiuaky.service.impl.BookServiceImpl_24133028; import com.kiemtragiuaky.service.impl.AuthorServiceImpl_24133028; import jakarta.servlet.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import java.io.IOException; import java.time.LocalDate; import java.math.BigDecimal; import java.util.*;
@WebServlet("/admin/books/*") public class AdminBookController_24133028 extends HttpServlet {
 private final BookServiceImpl_24133028 service=new BookServiceImpl_24133028(); private final AuthorServiceImpl_24133028 authors=new AuthorServiceImpl_24133028();
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{String p=r.getPathInfo();if(p==null||p.equals("/")){int page=page(r);long total=service.countBooks();int pages=Math.max(1,(int)Math.ceil(total/6.0));if(page>pages){s.sendRedirect(r.getContextPath()+"/admin/books?page="+pages);return;}r.setAttribute("books",service.getHomeBooks(page,6));r.setAttribute("currentPage",page);r.setAttribute("totalPages",pages);view(r,s,"list.jsp");}else if(p.equals("/create")){r.setAttribute("authors",authors.getAllAuthors());view(r,s,"form.jsp");}else if(p.equals("/view")){show(r,s,"view.jsp");}else if(p.equals("/edit")){show(r,s,"form.jsp");}else{s.sendError(404);}}
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{String p=r.getPathInfo();try{if(p.equals("/delete")){service.delete(Integer.parseInt(r.getParameter("id")));s.sendRedirect(r.getContextPath()+"/admin/books?success=deleted");return;}Book_24133028 b=read(r);Set<Integer> ids=authorIds(r);if(p.equals("/create")){service.save(b,ids);s.sendRedirect(r.getContextPath()+"/admin/books?success=created");}else if(p.equals("/edit")){b.setId(Integer.parseInt(r.getParameter("id")));service.update(b,ids);s.sendRedirect(r.getContextPath()+"/admin/books?success=updated");}else{s.sendError(404);}}catch(Exception e){r.setAttribute("error","Dữ liệu sách không hợp lệ hoặc thao tác thất bại.");r.setAttribute("authors",authors.getAllAuthors());view(r,s,"form.jsp");}}
 private Book_24133028 read(HttpServletRequest r){Book_24133028 b=new Book_24133028();b.setIsbn(Integer.valueOf(r.getParameter("isbn")));b.setTitle(r.getParameter("title")==null?"":r.getParameter("title").trim());b.setPublisher(r.getParameter("publisher"));b.setPrice(new BigDecimal(r.getParameter("price")));b.setDescription(r.getParameter("description"));b.setPublishDate(LocalDate.parse(r.getParameter("publishDate")));b.setCoverImage(r.getParameter("coverImage"));b.setQuantity(Integer.valueOf(r.getParameter("quantity")));if(b.getTitle().isBlank()||b.getPrice().signum()<0||b.getQuantity()<0)throw new IllegalArgumentException();return b;}
 private Set<Integer> authorIds(HttpServletRequest r){Set<Integer> ids=new LinkedHashSet<>();String[] values=r.getParameterValues("authorIds");if(values!=null)for(String v:values)ids.add(Integer.valueOf(v));return ids;}
 private void show(HttpServletRequest r,HttpServletResponse s,String jsp)throws ServletException,IOException{try{var b=service.findById(Integer.parseInt(r.getParameter("id"))).orElse(null);if(b==null){s.sendError(404);return;}r.setAttribute("book",b);r.setAttribute("authors",authors.getAllAuthors());Set<Integer> selected=new HashSet<>();b.getAuthors().forEach(a->selected.add(a.getId()));r.setAttribute("selectedAuthorIds",selected);view(r,s,jsp);}catch(Exception e){s.sendError(400);}}
 private int page(HttpServletRequest r){try{return Math.max(1,Integer.parseInt(r.getParameter("page")));}catch(Exception e){return 1;}}private void view(HttpServletRequest r,HttpServletResponse s,String f)throws ServletException,IOException{r.getRequestDispatcher("/WEB-INF/views/admin/books/"+f).include(r,s);}
}
