package com.kiemtragiuaky.controller;
import com.kiemtragiuaky.entity.Author_24133028; import com.kiemtragiuaky.service.impl.AuthorServiceImpl_24133028; import jakarta.servlet.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import java.io.IOException; import java.time.LocalDate;
@WebServlet("/admin/authors/*") public class AdminAuthorController_24133028 extends HttpServlet {
 private final AuthorServiceImpl_24133028 service=new AuthorServiceImpl_24133028();
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{String p=r.getPathInfo();if(p==null||p.equals("/")){int page=page(r);long total=service.count();int pages=Math.max(1,(int)Math.ceil(total/6.0));if(page>pages){s.sendRedirect(r.getContextPath()+"/admin/authors?page="+pages);return;}r.setAttribute("authors",service.getPage(page,6));r.setAttribute("currentPage",page);r.setAttribute("totalPages",pages);view(r,s,"list.jsp");}else if(p.equals("/create")){view(r,s,"form.jsp");}else if(p.equals("/view")){show(r,s,"view.jsp");}else if(p.equals("/edit")){show(r,s,"form.jsp");}else{s.sendError(404);}}
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws IOException,ServletException{String p=r.getPathInfo();try{if(p.equals("/create")){String n=r.getParameter("name");LocalDate d=date(r.getParameter("dateOfBirth"));if(n==null||n.trim().isEmpty()||d==null||d.isAfter(LocalDate.now()))throw new IllegalArgumentException("Tên và ngày sinh hợp lệ là bắt buộc.");Author_24133028 a=new Author_24133028();a.setName(n.trim());a.setDateOfBirth(d);service.save(a);s.sendRedirect(r.getContextPath()+"/admin/authors?success=created");}else if(p.equals("/edit")){Author_24133028 a=service.findById(Integer.parseInt(r.getParameter("id"))).orElseThrow();a.setName(r.getParameter("name").trim());a.setDateOfBirth(date(r.getParameter("dateOfBirth")));if(a.getName().isEmpty()||a.getDateOfBirth()==null||a.getDateOfBirth().isAfter(LocalDate.now()))throw new IllegalArgumentException("Thông tin tác giả không hợp lệ.");service.update(a);s.sendRedirect(r.getContextPath()+"/admin/authors?success=updated");}else if(p.equals("/delete")){service.delete(Integer.parseInt(r.getParameter("id")));s.sendRedirect(r.getContextPath()+"/admin/authors?success=deleted");}else{s.sendError(404);}}catch(IllegalStateException|IllegalArgumentException e){r.setAttribute("error",e.getMessage());if(p.equals("/delete"))s.sendRedirect(r.getContextPath()+"/admin/authors?error="+java.net.URLEncoder.encode(e.getMessage(),java.nio.charset.StandardCharsets.UTF_8));else view(r,s,"form.jsp");} }
 private void show(HttpServletRequest r,HttpServletResponse s,String jsp)throws ServletException,IOException{try{int id=Integer.parseInt(r.getParameter("id"));var a=service.findById(id).orElse(null);if(a==null){s.sendError(404);return;}r.setAttribute("author",a);view(r,s,jsp);}catch(NumberFormatException e){s.sendError(400);}}
 private int page(HttpServletRequest r){try{return Math.max(1,Integer.parseInt(r.getParameter("page")));}catch(Exception e){return 1;}} private LocalDate date(String v){try{return v==null||v.isBlank()?null:LocalDate.parse(v);}catch(Exception e){return null;}} private void view(HttpServletRequest r,HttpServletResponse s,String f)throws ServletException,IOException{r.getRequestDispatcher("/WEB-INF/views/admin/authors/"+f).include(r,s);}
}
