<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<title><c:out value="${book.title}" default="Chi tiết sách"/> | BookStore</title>
<section class="container py-5">
    <c:if test="${param.review == 'success'}"><div class="alert alert-success">Đánh giá đã được lưu.</div></c:if>
    <c:if test="${param.review == 'error'}"><div class="alert alert-danger">Dữ liệu đánh giá không hợp lệ.</div></c:if>
    <div class="row g-4"><div class="col-md-4"><c:choose><c:when test="${not empty book.coverImage}"><img class="img-fluid rounded book-cover" src="<c:url value='/assets/images/'/><c:out value='${book.coverImage}'/>" alt="Bìa sách" onerror="this.onerror=null;this.src='<c:url value='/assets/images/book-default.svg'/>'"/></c:when><c:otherwise><img class="img-fluid rounded book-cover" src="<c:url value='/assets/images/book-default.svg'/>" alt="Bìa sách mặc định"/></c:otherwise></c:choose></div>
        <div class="col-md-8"><h1 class="h2"><c:out value="${book.title}"/></h1><dl class="row"><dt class="col-sm-4">ISBN</dt><dd class="col-sm-8"><c:out value="${book.isbn}" default="Chưa cập nhật"/></dd><dt class="col-sm-4">Tác giả</dt><dd class="col-sm-8"><c:forEach items="${book.authors}" var="author" varStatus="status"><c:if test="${status.index > 0}">, </c:if><c:out value="${author.name}"/></c:forEach></dd><dt class="col-sm-4">Publisher</dt><dd class="col-sm-8"><c:out value="${book.publisher}" default="Chưa cập nhật"/></dd><dt class="col-sm-4">Publish date</dt><dd class="col-sm-8"><c:out value="${book.publishDate}" default="Chưa cập nhật"/></dd><dt class="col-sm-4">Quantity</dt><dd class="col-sm-8"><c:out value="${book.quantity}" default="0"/></dd><dt class="col-sm-4">Reviews</dt><dd class="col-sm-8"><c:out value="${fn:length(reviews)}"/></dd></dl></div>
    </div>
    <hr class="my-5"><h2 class="h4">Reviews (<c:out value="${fn:length(reviews)}"/>)</h2>
    <c:choose><c:when test="${not empty reviews}"><c:forEach items="${reviews}" var="review"><article class="border-bottom py-3"><strong><c:out value="${review.user.fullname}" default="${review.user.email}"/></strong><span class="ms-3 text-warning"><c:out value="${review.score}"/>/5</span><p class="mb-0 mt-2"><c:out value="${review.reviewText}"/></p></article></c:forEach></c:when><c:otherwise><p class="text-muted">Chưa có đánh giá.</p></c:otherwise></c:choose>
    <c:choose><c:when test="${not empty sessionScope.currentUser}"><h2 class="h4 mt-5">Thêm review</h2><form method="post" action="<c:url value='/book/review'/>"><input type="hidden" name="bookId" value="<c:out value='${book.id}'/>"/><div class="mb-3"><label class="form-label" for="rating">Rating</label><select class="form-select" id="rating" name="rating" required><option value="">Chọn điểm</option><c:forEach begin="1" end="5" var="score"><option value="${score}"><c:out value="${score}"/>/5</option></c:forEach></select></div><div class="mb-3"><label class="form-label" for="reviewText">Nội dung</label><textarea class="form-control" id="reviewText" name="reviewText" rows="4" required></textarea></div><button class="btn btn-primary" type="submit">Gửi review</button></form></c:when><c:otherwise><p class="mt-5"><a href="<c:url value='/login'/>">Đăng nhập</a> để viết review.</p></c:otherwise></c:choose>
</section>
