<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<title>Lịch sử đặt hàng | BookStore</title>
<section class="container py-5"><h1 class="h2 mb-4">Lịch sử đặt hàng</h1>
    <c:if test="${not empty filterError}"><div class="alert alert-warning"><c:out value="${filterError}"/></div></c:if>
    <form class="row g-2 mb-4" method="get" action="<c:url value='/orders'/>"><div class="col-sm-6 col-md-4"><label class="form-label" for="status">Lọc theo trạng thái</label><select class="form-select" id="status" name="status"><option value="ALL" ${selectedStatus == 'ALL' ? 'selected' : ''}>Tất cả đơn hàng</option><c:forEach items="${statuses}" var="status"><option value="${status.name()}" ${selectedStatus == status.name() ? 'selected' : ''}><c:out value="${status.label}"/></option></c:forEach></select></div><div class="col-auto align-self-end"><button class="btn btn-primary" type="submit">Lọc</button></div></form>
    <c:choose><c:when test="${not empty orders}"><div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th>Mã đơn</th><th>Ngày đặt</th><th>Trạng thái</th><th>Thanh toán</th><th>Tổng tiền</th><th></th></tr></thead><tbody><c:forEach items="${orders}" var="order"><tr><td>#<c:out value="${order.id}"/></td><td><c:out value="${order.createdAt}"/></td><td><span class="badge text-bg-primary"><c:out value="${order.status.label}"/></span></td><td><c:out value="${order.paymentMethod}"/></td><td><fmt:formatNumber value="${order.totalAmount}" type="currency" currencyCode="VND" maxFractionDigits="0"/></td><td><a class="btn btn-sm btn-outline-primary" href="<c:url value='/orders/detail'><c:param name='id' value='${order.id}'/></c:url>">Chi tiết</a></td></tr></c:forEach></tbody></table></div></c:when><c:otherwise><div class="alert alert-info">Chưa có đơn hàng phù hợp.</div></c:otherwise></c:choose>
</section>
